import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { createTestDatabase, type TestDatabase } from "../db/test-database";
import { SavedCollectionProfileRepository } from "../../server/collection-profiles/repository";
import { safeExportFilename, serializeProfiles } from "../../server/collection-profile-transfer/serializer";
import { parseImportFile, previewImportedProfile } from "../../server/collection-profile-transfer/parser";
import { ProfileImportPreviewManager } from "../../server/collection-profile-transfer/preview-manager";
import { confirmProfileImport, createImportPreview } from "../../server/collection-profile-transfer/service";
import { parseConfirmRequest, parseExportRequest } from "../../server/collection-profile-transfer/request-validation";
import type { SavedCollectionProfileInput } from "../../services/saved-collection-profile";

const databases:TestDatabase[]=[];afterEach(()=>databases.splice(0).forEach(db=>db.cleanup()));
const input=(overrides:Partial<SavedCollectionProfileInput>={}):SavedCollectionProfileInput=>({name:"내보내기 서울 AI",source:"jobkorea",basePresetId:"seoul-ai",strategy:"jobkorea_keyword",keyword:"AI",regions:["seoul"],pages:1,maxCandidates:10,allowListingFallback:true,exclusion:{keywords:["강사","웨이터"],fields:["title","category"]},isFavorite:true,...overrides});
const setup=()=>{const value=createTestDatabase();databases.push(value);return{db:value.database,repo:new SavedCollectionProfileRepository(value.database,()=>new Date("2026-08-06T00:00:00Z"))};};
const bytes=(value:unknown)=>new TextEncoder().encode(`${JSON.stringify(value)}\n`);

describe("saved profile export",()=>{
 it("writes versioned UTF-8 JSON without local identity or history",()=>{const {repo}=setup();const profile=repo.create(input());const {file,json}=serializeProfiles([profile],new Date("2026-08-06T01:02:03Z"));expect(file).toMatchObject({format:"nearby-jobs-collection-profiles",version:1,application:"NearbyJobsMap",exportedAt:"2026-08-06T01:02:03.000Z"});expect(file.profiles[0]).toMatchObject({name:profile.name,sourceRevision:1,sourceConfigurationHash:profile.configurationHash});expect(json).not.toContain(profile.id);expect(json).not.toContain("ingestion_runs");expect(JSON.parse(json).profiles[0].name).toBe("내보내기 서울 AI");});
 it("retains explicit selected order",()=>{const {repo}=setup();const a=repo.create(input());const b=repo.create(input({name:"내보내기 경기 AI",basePresetId:"gyeonggi-ai",regions:["gyeonggi"],isFavorite:false}));expect(serializeProfiles([b,a]).file.profiles.map(p=>p.name)).toEqual([b.name,a.name]);});
 it("creates bounded safe Korean filenames",()=>{const {repo}=setup();const profile=repo.create(input({name:"서울/AI:프로필"}));const name=safeExportFilename([profile],new Date("2026-08-06T01:02:03Z"));expect(name).toMatch(/^nearby-jobs-profile-서울-AI-프로필-20260806\.json$/u);expect(name).not.toContain("/");});
});

describe("strict import parsing and preview",()=>{
 function exported(){const {repo}=setup();const profile=repo.create(input());return serializeProfiles([profile]).file;}
 it("parses supported v1 and rejects malformed, empty, format and version",()=>{const file=exported();expect(parseImportFile(bytes(file)).profiles).toHaveLength(1);expect(()=>parseImportFile(new Uint8Array())).toThrow(/빈 파일/);expect(()=>parseImportFile(bytes("bad"))).toThrow(/구조/);expect(()=>parseImportFile(bytes({...file,format:"other"}))).toThrow(/형식/);expect(()=>parseImportFile(bytes({...file,version:2}))).toThrow(/버전/);});
 it("rejects duplicate export keys, unexpected fields and excess size",()=>{const file=exported();expect(()=>parseImportFile(bytes({...file,profiles:[file.profiles[0],file.profiles[0]]}))).toThrow(/exportKey/);expect(()=>parseImportFile(bytes({...file,command:"run"}))).toThrow(/필드/);expect(()=>parseImportFile(new Uint8Array(512*1024+1))).toThrow(/512/);});
 it("reuses profile validation and reports imported hash mismatch",()=>{const {repo}=setup();const profile=repo.create(input());const file=serializeProfiles([profile]).file;const raw=parseImportFile(bytes(file)).profiles[0]!;const preview=previewImportedProfile({...raw,sourceConfigurationHash:"untrusted"},0,[]);expect(preview.state).toBe("valid_new");expect(preview.configurationValid).toBe(true);expect(preview.exportedHashMatches).toBe(false);expect(preview.computedConfigurationHash).toBe(profile.configurationHash);});
 it("detects identical, name conflict, and same configuration with another name",()=>{const {repo}=setup();const existing=repo.create(input());const raw=parseImportFile(bytes(serializeProfiles([existing]).file)).profiles[0]!;expect(previewImportedProfile(raw,0,[existing]).state).toBe("identical_existing");expect(previewImportedProfile({...raw,pages:2},0,[existing]).state).toBe("name_conflict_different_configuration");expect(previewImportedProfile({...raw,name:"다른 서울 프로필"},0,[existing]).state).toBe("same_configuration_different_name");});
 it("keeps invalid imported profiles visible with reasons",()=>{const {repo}=setup();const file=serializeProfiles([repo.create(input())]).file;const raw=parseImportFile(bytes(file)).profiles[0]!;const preview=previewImportedProfile({...raw,pages:99},0,[]);expect(preview.configurationValid).toBe(false);expect(preview.validationErrors.length).toBe(1);expect(preview.availableActions).toEqual([]);});
});

describe("preview tokens and transactional confirmation",()=>{
 it("expires, caps, and consumes opaque previews",()=>{let now=0;const manager=new ProfileImportPreviewManager(()=>now,100,1);const base={format:"nearby-jobs-collection-profiles" as const,version:1 as const,filename:"x.json",fileSize:1,profileCount:0,profiles:[]};const first=manager.create(base,"hash");expect(first.previewToken).not.toContain("hash");expect(()=>manager.create(base,"hash2")).toThrow(/최대 5개/);manager.consume(first.previewToken);expect(()=>manager.require(first.previewToken)).toThrow();const second=manager.create(base,"hash2");now=101;expect(()=>manager.require(second.previewToken)).toThrow(/찾을 수/);});
 it("creates new opaque IDs at revision one and preserves the authoritative hash",()=>{const {db,repo}=setup();const source=repo.create(input());const file=serializeProfiles([source]).file;repo.delete(source.id);const parsed=parseImportFile(bytes(file));const manager=new ProfileImportPreviewManager();const preview=createImportPreview(db,parsed.profiles,{filename:"profiles.json",fileSize:bytes(file).length,payloadHash:parsed.payloadHash},manager);const result=confirmProfileImport(db,preview.previewToken,[{exportKey:preview.profiles[0]!.exportKey,action:"create"}],manager);expect(result.created).toBe(1);expect(result.profiles[0]!.id).not.toBe(source.id);expect(result.profiles[0]!.revision).toBe(1);expect(result.profiles[0]!.configurationHash).toBe(source.configurationHash);expect(result.profiles[0]!.lastUsedAt).toBeNull();expect(result.profiles[0]!.isFavorite).toBe(true);});
 it("supports skip, rename-and-create, and conservative replace",()=>{const {db,repo}=setup();const existing=repo.create(input());const file=serializeProfiles([existing]).file;const parsed=parseImportFile(bytes(file));const manager=new ProfileImportPreviewManager();let preview=createImportPreview(db,parsed.profiles,{filename:"x.json",fileSize:1,payloadHash:parsed.payloadHash},manager);expect(confirmProfileImport(db,preview.previewToken,[{exportKey:preview.profiles[0]!.exportKey,action:"skip"}],manager).skipped).toBe(1);
   preview=createImportPreview(db,parsed.profiles,{filename:"x.json",fileSize:1,payloadHash:parsed.payloadHash},manager);const renamed=confirmProfileImport(db,preview.previewToken,[{exportKey:preview.profiles[0]!.exportKey,action:"rename_and_create",newName:"가져온 서울 AI"}],manager).profiles[0]!;expect(renamed.configurationHash).toBe(existing.configurationHash);
   const changed={...parsed.profiles[0]!,pages:2};preview=createImportPreview(db,[changed],{filename:"x.json",fileSize:1,payloadHash:"changed"},manager);const entry=preview.profiles[0]!;const result=confirmProfileImport(db,preview.previewToken,[{exportKey:entry.exportKey,action:"replace_existing",expectedRevision:1,replaceConfirmed:true}],manager);expect(result.replaced).toBe(1);expect(result.profiles[0]!.revision).toBe(2);});
 it("rolls back every creation when a later action conflicts",()=>{const {db,repo}=setup();const original=repo.create(input());const file=serializeProfiles([original]).file;repo.delete(original.id);const raw=parseImportFile(bytes(file)).profiles[0]!;const manager=new ProfileImportPreviewManager();const preview=createImportPreview(db,[raw,{...raw,exportKey:"second",name:raw.name}],{filename:"x.json",fileSize:1,payloadHash:"x"},manager);expect(()=>confirmProfileImport(db,preview.previewToken,preview.profiles.map(p=>({exportKey:p.exportKey,action:"create"})),manager)).toThrow();expect(repo.count()).toBe(0);});
 it("rejects stale replacement revision",()=>{const {db,repo}=setup();const existing=repo.create(input());const file=serializeProfiles([existing]).file;const raw={...parseImportFile(bytes(file)).profiles[0]!,pages:2};const manager=new ProfileImportPreviewManager();const preview=createImportPreview(db,[raw],{filename:"x",fileSize:1,payloadHash:"x"},manager);repo.update(existing.id,1,input({pages:2}));expect(()=>confirmProfileImport(db,preview.previewToken,[{exportKey:preview.profiles[0]!.exportKey,action:"replace_existing",expectedRevision:1,replaceConfirmed:true}],manager)).toThrow(/변경/);});
});

describe("transfer request validation",()=>{
 it("accepts selected and all exports while rejecting duplicates and commands",()=>{expect(parseExportRequest({profileIds:["123e4567-e89b-42d3-a456-426614174000"]})).toHaveProperty("profileIds");expect(parseExportRequest({allProfiles:true})).toEqual({allProfiles:true});expect(()=>parseExportRequest({profileIds:["123e4567-e89b-42d3-a456-426614174000","123e4567-e89b-42d3-a456-426614174000"]})).toThrow();expect(()=>parseExportRequest({allProfiles:true,command:"x"})).toThrow();});
 it("strictly validates confirm actions",()=>{expect(parseConfirmRequest({previewToken:"opaque-preview-token",actions:[{exportKey:"a",action:"skip"}]}).actions).toHaveLength(1);expect(()=>parseConfirmRequest({previewToken:"opaque-preview-token",actions:[{exportKey:"a",action:"skip",sql:"x"}]})).toThrow();expect(()=>parseConfirmRequest({previewToken:"opaque-preview-token",actions:[{exportKey:"a",action:"skip"},{exportKey:"a",action:"create"}]})).toThrow();});
});
