import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));
import { POST as exportProfiles } from "../../app/api/collection-profiles/export/route";
import { POST as previewImport } from "../../app/api/collection-profiles/import/preview/route";
import { POST as confirmImport } from "../../app/api/collection-profiles/import/confirm/route";
import { createTestDatabase,type TestDatabase } from "../db/test-database";
import { SavedCollectionProfileRepository } from "../../server/collection-profiles/repository";

let testDatabase:TestDatabase;beforeEach(()=>{testDatabase=createTestDatabase();process.env.NEARBY_JOBS_DB_PATH=testDatabase.path;process.env.NEARBY_JOBS_ENABLE_COLLECTION_UI="1";});afterEach(()=>{testDatabase.cleanup();delete process.env.NEARBY_JOBS_DB_PATH;delete process.env.NEARBY_JOBS_ENABLE_COLLECTION_UI;});
const input={name:"API 서울 AI",source:"jobkorea" as const,basePresetId:"seoul-ai",strategy:"jobkorea_keyword" as const,keyword:"AI",regions:["seoul" as const],pages:1,maxCandidates:10,allowListingFallback:true,exclusion:{keywords:["강사"],fields:["title" as const]},isFavorite:true};
const request=(path:string,body:BodyInit,contentType?:string,host="localhost")=>new Request(`http://${host}${path}`,{method:"POST",headers:{origin:`http://${host}`,...(contentType?{"content-type":contentType}:{})},body});

describe("profile transfer APIs",()=>{
 it("exports selected profiles with download headers and no local ID",async()=>{const profile=new SavedCollectionProfileRepository(testDatabase.database).create(input);const response=await exportProfiles(request("/api/collection-profiles/export",JSON.stringify({profileIds:[profile.id]}),"application/json"));expect(response.status).toBe(200);expect(response.headers.get("content-type")).toBe("application/json; charset=utf-8");expect(response.headers.get("content-disposition")).toContain("filename*=UTF-8''");const body=await response.json();expect(body.profiles[0].name).toBe(input.name);expect(JSON.stringify(body)).not.toContain(profile.id);});
 it("previews without writing and confirms a transaction",async()=>{const source=new SavedCollectionProfileRepository(testDatabase.database).create(input);const exported=await (await exportProfiles(request("/api/collection-profiles/export",JSON.stringify({profileIds:[source.id]}),"application/json"))).text();new SavedCollectionProfileRepository(testDatabase.database).delete(source.id);const form=new FormData();form.append("file",new File([exported],"profiles.json",{type:"application/json"}));const previewResponse=await previewImport(request("/api/collection-profiles/import/preview",form));expect(previewResponse.status).toBe(200);expect(new SavedCollectionProfileRepository(testDatabase.database).count()).toBe(0);const preview=await previewResponse.json();const confirm=await confirmImport(request("/api/collection-profiles/import/confirm",JSON.stringify({previewToken:preview.previewToken,actions:[{exportKey:preview.profiles[0].exportKey,action:"create"}]}),"application/json"));expect(confirm.status).toBe(200);expect((await confirm.json()).created).toBe(1);expect(new SavedCollectionProfileRepository(testDatabase.database).count()).toBe(1);});
 it("preserves local-only, origin, strict-field and sanitized-error boundaries",async()=>{const remote=await exportProfiles(request("/api/collection-profiles/export",JSON.stringify({allProfiles:true}),"application/json","example.com"));expect(remote.status).toBe(403);const rejected=await exportProfiles(request("/api/collection-profiles/export",JSON.stringify({allProfiles:true,command:"run",sql:"select"}),"application/json"));expect(rejected.status).toBe(400);const text=JSON.stringify(await rejected.json());expect(text).not.toMatch(/stack|database path|nearby-jobs\.sqlite/iu);delete process.env.NEARBY_JOBS_ENABLE_COLLECTION_UI;expect((await exportProfiles(request("/api/collection-profiles/export",JSON.stringify({allProfiles:true}),"application/json"))).status).toBe(403);});
});
