// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ProfileComparisonPanel } from "../../components/collection/ProfileComparisonPanel";
import type { SavedCollectionProfile } from "../../services/saved-collection-profile";

afterEach(() => { cleanup(); vi.unstubAllGlobals(); window.history.replaceState(null, "", "/"); });
const profile = (id: string, name: string, source: "jobkorea" | "albamon" = "jobkorea"): SavedCollectionProfile => ({ id, name, source, basePresetId: source === "jobkorea" ? "capital-ai" : "albamon-capital-today", strategy: source === "jobkorea" ? "jobkorea_keyword" : "albamon_today", keyword: source === "jobkorea" ? "AI" : null, regions: ["seoul", "gyeonggi"], pages: 1, maxCandidates: 10, allowListingFallback: source === "jobkorea", exclusion: { keywords: name.endsWith("A") ? ["강사", "웨이터"] : ["강사", "전기"], fields: ["title", "category"] }, isFavorite: name.endsWith("A"), revision: 1, configurationHash: `hash-${id}`, createdAt: "2026-08-01T00:00:00Z", updatedAt: "2026-08-01T00:00:00Z", lastUsedAt: null });
const a = profile("11111111-1111-4111-8111-111111111111", "프로필 A"); const b = profile("22222222-2222-4222-8222-222222222222", "프로필 B");
const result = { generatedAt: "2026-08-06T00:00:00Z", period: "30d", revisionScope: "current", profiles: [a, b], configurationDifferences: [{ field: "regions", label: "지역", same: true, values: [{ profileId: a.id, value: "seoul,gyeonggi" }, { profileId: b.id, value: "seoul,gyeonggi" }] }], differenceSummary: ["공통 소스: 잡코리아", "공통 제외 키워드 1개"], exclusions: { commonKeywords: ["강사"], commonKeywordsTruncated: false, uniqueKeywords: [{ profileId: a.id, keywords: ["웨이터"], truncated: false }, { profileId: b.id, keywords: ["전기"], truncated: false }], commonFields: ["title", "category"], uniqueFields: [{ profileId: a.id, fields: [] }, { profileId: b.id, fields: [] }], profilesWithoutExclusions: [] }, performance: [a, b].map((p) => ({ profileId: p.id, writeRuns: 0, completedRuns: 0, failedRuns: 0, latestRunAt: null, latestRunStatus: null, selectedCandidates: null, candidatesBeforeExclusion: null, excludedCandidates: null, candidatesAfterExclusion: null, detailAttempts: null, successfulDetailParses: null, listingFallbacks: null, inserted: 0, updated: 0, unchanged: 0, lowerCompletenessSkips: 0, failedItems: 0, totalDurationMs: null, averageDurationMs: null, averageSelectedCandidates: null, exclusionRate: null, failureRate: null, insertUpdateRate: null, validRecordYield: null, listingFallbackRate: null, revisionsRepresented: [], latestRunRevision: null, currentRevisionUsed: false, historicalConfigurationHashesDiffer: false, recentRuns: [] })), overlap: { pairs: [{ profileAId: a.id, profileBId: b.id, applicable: true, source: "jobkorea", profileAIdentities: 0, profileBIdentities: 0, sharedIdentities: 0, uniqueToA: 0, uniqueToB: 0, overlapPercentage: null, jaccardSimilarity: null, sharedSampleIds: [], uniqueSampleIdsA: [], uniqueSampleIdsB: [] }], sharedByAll: null, sharedByAllSampleIds: [], uniqueByProfile: [], crossSourceLimited: false }, legacyLimitations: [] };

describe("ProfileComparisonPanel", () => {
  it("selects two profiles, compares, renders differences/no-run/overlap, and persists opaque URL state", async () => {
    const fetchMock = vi.fn(async (input: RequestInfo | URL, _init?: RequestInit) => String(input).includes("comparison") ? new Response(JSON.stringify({ comparison: result }), { status: 200 }) : new Response(JSON.stringify({ profiles: [a, b] }), { status: 200 })); vi.stubGlobal("fetch", fetchMock);
    render(<ProfileComparisonPanel enabled activeRun={null} refreshKey={0} onOpenExecution={vi.fn()} />); expect(await screen.findByText(/프로필 A/)).toBeInTheDocument();
    fireEvent.click(screen.getByLabelText(/프로필 A/)); fireEvent.click(screen.getByLabelText(/프로필 B/)); expect(screen.getByText(/현재 2개 선택/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "비교하기" }));
    expect(await screen.findByRole("heading", { name: "현재 구성 비교" })).toBeInTheDocument(); expect(screen.getByText("공통 제외 키워드 1개")).toBeInTheDocument(); expect(screen.getAllByText("실행 기록 없음").length).toBeGreaterThan(0); expect(screen.getAllByText("정보 없음").length).toBeGreaterThan(0);
    expect(window.location.search).toContain("tab=compare"); expect(window.location.search).toContain(a.id);
    fireEvent.change(screen.getByLabelText("기간"), { target: { value: "all" } }); await waitFor(() => expect(fetchMock.mock.calls.some((call) => String(call[1]?.body).includes('"period":"all"'))).toBe(true));
  });
  it("shows the two-profile empty state and local-disabled explanation", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ profiles: [a] }), { status: 200 }))); const onOpen = vi.fn(); const { rerender } = render(<ProfileComparisonPanel enabled activeRun={null} refreshKey={0} onOpenExecution={onOpen} />);
    expect(await screen.findByText(/2개 이상 필요/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: /기본 프리셋/ })); expect(onOpen).toHaveBeenCalled(); rerender(<ProfileComparisonPanel enabled={false} activeRun={null} refreshKey={0} onOpenExecution={onOpen} />); expect(screen.getByRole("status")).toHaveTextContent("비활성화");
  });
});
