import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const read=(path:string)=>readFileSync(resolve(process.cwd(),path),"utf8");

describe("public first-user hardening contracts",()=>{
  it("uses explicit official Node 24 GitHub actions without weakening CI",()=>{const ci=read(".github/workflows/ci.yml"),uses=ci.split(/\r?\n/).filter(line=>line.includes("uses:"));expect(uses).toEqual(expect.arrayContaining([expect.stringContaining("actions/checkout@v7.0.1"),expect.stringContaining("actions/setup-node@v7.0.0")]));expect(uses).toHaveLength(2);expect(ci).toContain("contents: read");expect(ci).toContain('NEARBY_JOBS_ENABLE_COLLECTION_UI: "0"');expect(ci).toContain("$RUNNER_TEMP/nearby-jobs-ci.sqlite");expect(ci).not.toMatch(/deploy|publish|collect:(?:jobkorea|albamon)/i)});
  it("bounds Chromium installation and separates default from strict failure",()=>{const install=read("scripts/install.ps1"),browser=read("scripts/playwright-browser.ps1");expect(install).toContain("[ValidateRange(1, 30)]");expect(install).toContain("RequireBrowserInstall");expect(install).toContain("비수집 기능 설치는 계속됩니다");expect(browser).toContain("WaitForExit($TimeoutMinutes * 60 * 1000)");expect(browser).toContain("taskkill.exe /PID $ProcessId /T /F");expect(browser).not.toMatch(/taskkill\.exe\s+\/IM|node\.exe\s+\/F/i)});
  it("provides repair and collection-readiness checks with no navigation",()=>{const installer=read("scripts/install-browser.ps1"),doctor=read("scripts/doctor.ps1"),browser=read("scripts/playwright-browser.ps1");expect(installer).toContain("CheckOnly");expect(installer).toContain("Test-PlaywrightChromiumLaunch");expect(doctor).toContain("RequireCollectionReady");expect(browser).toContain("about:blank");expect(installer+doctor+browser).not.toMatch(/jobkorea|albamon|openstreetmap|page\.goto/i)});
  it("keeps support bundles bounded, redacted, manual, and locally audited",()=>{const bundle=read("scripts/support-bundle.ps1"),audit=read("scripts/support-bundle-audit.ps1");expect(bundle).toContain("<PROJECT_ROOT>");expect(bundle).toContain("environmentVariableNames");expect(bundle).toContain("Get-SafeDatabaseCounts");expect(bundle).toContain("never uploaded automatically");for(const term of["job and company data","environment values","credentials and cookies"])expect(bundle).toContain(term);expect(audit).toContain("SQLite format 3");expect(audit).toContain("does not guarantee anonymity")});
  it("documents repair, support review, and the current release",()=>{expect(read("docs/WINDOWS_INSTALL.md")).toContain("install-browser.ps1");expect(read("docs/TROUBLESHOOTING.md")).toContain("Chromium installation appears stuck");expect(read("CHANGELOG.md")).toContain("## v0.2.1");expect(read("package.json")).toContain('"version": "0.2.1"')});
});
