import "server-only";
import type Database from "better-sqlite3";
import {createSavedViewId,normalizeViewName,SavedJobViewError,validateSavedJobViewInput,type SavedJobView,type SavedJobViewInput}from"../../services/saved-job-view";
type Row=Record<string,unknown>;
const map=(row:Row):SavedJobView=>({id:String(row.id),name:String(row.name),filters:JSON.parse(String(row.filter_json)) as SavedJobView["filters"],sort:String(row.sort_key??"newest") as SavedJobView["sort"],isFavorite:Number(row.is_favorite)===1,isDefault:Number(row.is_default)===1,createdAt:String(row.created_at),updatedAt:String(row.updated_at),lastUsedAt:typeof row.last_used_at==="string"?row.last_used_at:null});
export class SavedJobViewRepository{
 constructor(private db:Database.Database,private now=()=>new Date()){}
 list(){return(this.db.prepare("SELECT * FROM saved_job_views ORDER BY is_favorite DESC, COALESCE(last_used_at,updated_at) DESC, normalized_name").all()as Row[]).map(map)}
 get(id:string){const r=this.db.prepare("SELECT * FROM saved_job_views WHERE id=?").get(id)as Row|undefined;return r?map(r):null}
 create(raw:SavedJobViewInput){const input=validateSavedJobViewInput(raw),id=createSavedViewId(),now=this.now().toISOString();try{this.db.transaction(()=>{if(input.isDefault)this.db.prepare("UPDATE saved_job_views SET is_default=0").run();this.db.prepare("INSERT INTO saved_job_views(id,name,normalized_name,filter_json,sort_key,is_favorite,is_default,created_at,updated_at,last_used_at) VALUES(?,?,?,?,?,?,?,?,?,NULL)").run(id,input.name,normalizeViewName(input.name),JSON.stringify(input.filters),input.sort,input.isFavorite?1:0,input.isDefault?1:0,now,now)})();}catch(error){if(String(error).includes("UNIQUE"))throw new SavedJobViewError("VIEW_NAME_CONFLICT","같은 이름의 저장 보기가 있습니다.",409);throw error}return this.get(id)!}
 update(id:string,raw:SavedJobViewInput){if(!this.get(id))throw new SavedJobViewError("VIEW_NOT_FOUND","저장 보기를 찾을 수 없습니다.",404);const input=validateSavedJobViewInput(raw),now=this.now().toISOString();try{this.db.transaction(()=>{if(input.isDefault)this.db.prepare("UPDATE saved_job_views SET is_default=0 WHERE id<>?").run(id);this.db.prepare("UPDATE saved_job_views SET name=?,normalized_name=?,filter_json=?,sort_key=?,is_favorite=?,is_default=?,updated_at=? WHERE id=?").run(input.name,normalizeViewName(input.name),JSON.stringify(input.filters),input.sort,input.isFavorite?1:0,input.isDefault?1:0,now,id)})();}catch(error){if(String(error).includes("UNIQUE"))throw new SavedJobViewError("VIEW_NAME_CONFLICT","같은 이름의 저장 보기가 있습니다.",409);throw error}return this.get(id)!}
 markUsed(id:string){const now=this.now().toISOString();if(this.db.prepare("UPDATE saved_job_views SET last_used_at=? WHERE id=?").run(now,id).changes===0)throw new SavedJobViewError("VIEW_NOT_FOUND","저장 보기를 찾을 수 없습니다.",404);return this.get(id)!}
 delete(id:string){if(this.db.prepare("DELETE FROM saved_job_views WHERE id=?").run(id).changes===0)throw new SavedJobViewError("VIEW_NOT_FOUND","저장 보기를 찾을 수 없습니다.",404)}
}
