import { createHash } from "node:crypto";
import { mkdirSync, rmSync, cpSync } from "node:fs";
import { createServer } from "node:net";
import { join, resolve } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import Database from "better-sqlite3";
import { chromium, type BrowserContext, type Page } from "playwright";
import { applyMigrations } from "../src/db/migrate";
import { seedFictionalDemoJobs } from "../src/db/services/demo-seed-service";
import { SCREENSHOT_SPECS, SCREENSHOT_WORK_RELATIVE, assertIsolatedScreenshotDatabase, isAllowedBrowserUrl } from "./docs/screenshot-contracts";

const root = process.cwd(); const work = resolve(root, SCREENSHOT_WORK_RELATIVE); const databasePath = join(work, "nearby-jobs-screenshots.sqlite"); const output = join(work, "output");
assertIsolatedScreenshotDatabase(databasePath, root);
const titles = ["AI 데이터 운영 보조","온라인 콘텐츠 검수","물류센터 입출고 지원","지역정보 데이터 정리","고객지원 사무보조","이미지 라벨링 작업자","서비스 운영 어시스턴트","단기 재고조사 보조"];
const companies = ["새봄데이터","한빛로컬랩","모아물류","푸른지도","다온서비스","봄날콘텐츠","우리동네테크","해솔운영센터"];
const fixedTimes = ["2026-08-05T09:00:00+09:00","2026-08-04T10:30:00+09:00","2026-08-02T14:00:00+09:00","2026-07-28T11:00:00+09:00"];
const profileIds = ["11111111-1111-4111-8111-111111111111","22222222-2222-4222-8222-222222222222","33333333-3333-4333-8333-333333333333"];

function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function seed(): void {
  mkdirSync(work,{recursive:true}); mkdirSync(output,{recursive:true}); const db = new Database(databasePath); db.pragma("foreign_keys=ON");
  try {
    applyMigrations(db); seedFictionalDemoJobs(db);
    const baseRows = db.prepare("SELECT * FROM jobs ORDER BY id").all() as Record<string,unknown>[];
    const columns = (db.pragma("table_info(jobs)") as Array<{name:string}>).map(({name})=>name);
    const insert = db.prepare(`INSERT INTO jobs (${columns.join(",")}) VALUES (${columns.map(()=>"?").join(",")})`);
    for(let i=10;i<24;i++){const row={...baseRows[i%baseRows.length]}; row.id=`demo:screen-${String(i+1).padStart(3,"0")}`; row.source=i%3===0?"albamon":"jobkorea"; row.source_posting_id=`demo-screen-${String(i+1).padStart(3,"0")}`; row.title=titles[i%titles.length]; row.company_name=companies[i%companies.length]; row.normalized_company_name=companies[i%companies.length]; row.source_fixture_reference=`screenshot-demo:${i+1}`; row.content_hash=hash({i,title:row.title}); row.created_at=fixedTimes[i%fixedTimes.length]; row.updated_at=row.created_at; row.posted_at=`2026-08-${String(5-(i%4)).padStart(2,"0")}`; row.collected_at=row.created_at; row.last_verified_at=row.created_at; row.observed_at=row.created_at; insert.run(...columns.map(c=>row[c]??null));
      const original=String(baseRows[i%baseRows.length]!.id); const id=String(row.id);
      for(const r of db.prepare("SELECT category,position FROM job_categories WHERE job_id=?").all(original) as Array<{category:string;position:number}>) db.prepare("INSERT INTO job_categories VALUES(?,?,?)").run(id,r.category,r.position);
      for(const r of db.prepare("SELECT employment_type,position FROM job_employment_types WHERE job_id=?").all(original) as Array<{employment_type:string;position:number}>) db.prepare("INSERT INTO job_employment_types VALUES(?,?,?)").run(id,r.employment_type,r.position);
      for(const r of db.prepare("SELECT position,original_text,road_address,parcel_address,city,district,neighborhood,nearest_station,latitude,longitude,accuracy,is_headquarters_only,created_at,updated_at FROM workplaces WHERE job_id=?").all(original) as Record<string,unknown>[]) db.prepare("INSERT INTO workplaces(job_id,position,original_text,road_address,parcel_address,city,district,neighborhood,nearest_station,latitude,longitude,accuracy,is_headquarters_only,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,...Object.values(r));
    }
    const all=db.prepare("SELECT id,source,source_posting_id FROM jobs ORDER BY id").all() as Array<{id:string;source:string;source_posting_id:string}>;
    const updateDemo=db.prepare("UPDATE jobs SET title=?,company_name=?,normalized_company_name=?,record_kind='fictional_demo',is_fictional=1,provenance_kind='fictional_demo',evidence_type='fictional_demo',provenance_evidence_type='fictional_demo',observation_kind='bounded_listing_collection',detail_access_status='not_attempted',permission_status='unverified',collection_preset_label='문서 화면용 데모',collection_preset_id=CASE WHEN source='jobkorea' THEN 'capital-ai' ELSE 'albamon-capital-today' END,collection_keyword=CASE WHEN source='jobkorea' THEN 'AI' ELSE NULL END,requested_regions_json=?,normalized_regions_json=?,region_normalization_confidence=?,observed_at=?,collected_at=?,last_verified_at=?,source_url='',canonical_url=NULL,description_summary='정제된 문서 화면용 가상 공고입니다.' WHERE id=?");
    all.forEach((job,i)=>{const regions=i<10?["seoul"]:i<20?["gyeonggi"]:[];const observed=fixedTimes[i%fixedTimes.length];updateDemo.run(titles[i%titles.length],companies[i%companies.length],companies[i%companies.length],JSON.stringify(regions),JSON.stringify(regions),regions.length?"exact":"unknown",observed,observed,observed,job.id);});
    db.exec("DELETE FROM job_provenance_history; DELETE FROM job_change_events; DELETE FROM job_observations; DELETE FROM ingestion_items; DELETE FROM ingestion_runs;");
    const profiles=[
      {id:profileIds[0],name:"서울 AI 운영직",source:"jobkorea",basePresetId:"seoul-ai",strategy:"jobkorea_keyword",keyword:"AI",regions:["seoul"],pages:1,maxCandidates:10,allowListingFallback:true,exclusion:{keywords:["영업","보험"],fields:["title","category"]},favorite:1},
      {id:profileIds[1],name:"경기 데이터 라벨링",source:"jobkorea",basePresetId:"gyeonggi-ai",strategy:"jobkorea_keyword",keyword:"데이터 라벨링",regions:["gyeonggi"],pages:2,maxCandidates:20,allowListingFallback:true,exclusion:{keywords:["강사","운전"],fields:["title","category"]},favorite:0},
      {id:profileIds[2],name:"수도권 단기 사무보조",source:"albamon",basePresetId:"albamon-capital-today",strategy:"albamon_today",keyword:null,regions:["seoul","gyeonggi"],pages:2,maxCandidates:15,allowListingFallback:false,exclusion:{keywords:["텔레마케팅"],fields:["title"]},favorite:0},
    ];
    for(const p of profiles){const configurationHash=hash({source:p.source,basePresetId:p.basePresetId,strategy:p.strategy,keyword:p.keyword,regions:p.regions,pages:p.pages,maxCandidates:p.maxCandidates,allowListingFallback:p.allowListingFallback,exclusion:p.exclusion});db.prepare("INSERT INTO saved_collection_profiles VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(p.id,p.name,p.name.toLocaleLowerCase("en-US"),p.source,p.basePresetId,p.strategy,p.keyword,JSON.stringify(p.regions),p.pages,p.maxCandidates,p.allowListingFallback?1:0,JSON.stringify(p.exclusion.keywords),JSON.stringify(p.exclusion.fields),p.favorite,1,configurationHash,fixedTimes[3],fixedTimes[0],fixedTimes[0]);}
    const runData=[
      ["demo-run-seoul",0,"jobkorea","completed",profileIds[0],"서울 AI 운영직",8,4,1,2,0,1,10,2,"[\"영업\",\"보험\"]","[\"title\",\"category\"]"],
      ["demo-run-gyeonggi",1,"jobkorea","completed",profileIds[1],"경기 데이터 라벨링",12,3,2,5,1,1,15,3,"[\"강사\",\"운전\"]","[\"title\",\"category\"]"],
      ["demo-run-albamon",2,"albamon","completed",profileIds[2],"수도권 단기 사무보조",10,5,1,4,0,0,12,2,"[\"텔레마케팅\"]","[\"title\"]"],
      ["demo-run-failed",3,"jobkorea","failed",profileIds[1],"경기 데이터 라벨링",4,0,0,0,0,4,4,0,"[\"강사\"]","[\"title\"]"],
    ] as const;
    for(const [id,index,source,status,pid,pname,selected,inserted,updated,unchanged,skipped,failed,candidatesBefore,excluded,keywords,fields] of runData){const p=profiles.find(x=>x.id===pid)!;const ph=hash({source:p.source,basePresetId:p.basePresetId,strategy:p.strategy,keyword:p.keyword,regions:p.regions,pages:p.pages,maxCandidates:p.maxCandidates,allowListingFallback:p.allowListingFallback,exclusion:p.exclusion});db.prepare(`INSERT INTO ingestion_runs(id,source,ingestion_type,status,started_at,completed_at,input_record_count,inserted_count,updated_count,unchanged_count,skipped_count,failed_count,error_summary,permission_status,max_details,selected_detail_count,dry_run,search_page_count,exclusion_keywords_json,exclusion_fields_json,exclusion_config_hash,excluded_candidate_count,selected_candidate_count_after_exclusion,saved_profile_id,saved_profile_name,saved_profile_revision,saved_profile_configuration_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,?,?,?)`).run(id,source,source==="albamon"?"albamon_listing_collection":"jobkorea_one_shot_transport",status,fixedTimes[index],fixedTimes[index],candidatesBefore,inserted,updated,unchanged,skipped,failed,status==="failed"?"문서용 합성 전송 실패":null,"unverified",selected,source==="jobkorea"?selected:0,p.pages,keywords,fields,hash({keywords,fields}),excluded,selected,pid,pname,1,ph,fixedTimes[index]);
      for(let j=0;j<selected;j++){const candidates=all.filter(x=>x.source===source);const job=candidates[j%candidates.length]!;const result=status==="failed"?"failed":j<inserted?"inserted":j<inserted+updated?"updated":"unchanged";const diagnostics=status==="failed"?["TRANSPORT_FAILED"]:source==="jobkorea"?["JOBKOREA_LISTING_FALLBACK_USED"]:[];db.prepare("INSERT INTO ingestion_items(ingestion_run_id,source,source_posting_id,canonical_job_id,result,diagnostic_codes,content_hash,created_at) VALUES(?,?,?,?,?,?,?,?)").run(id,source,job.source_posting_id,result==="failed"?null:job.id,result,JSON.stringify(diagnostics),result==="failed"?null:hash(job),fixedTimes[index]);}
    }
    for(const [i,job] of all.entries()){const observed=fixedTimes[i%fixedTimes.length];db.prepare("INSERT INTO job_observations(observation_key,job_id,ingestion_run_id,source,source_posting_id,observed_at,content_hash,completeness,posting_status,snapshot_json,observation_kind) SELECT ?,id,NULL,source,source_posting_id,?,content_hash,'listing_only',posting_status,json_object('title',title,'company',company_name,'location',address_original_text,'salary',salary_original_text,'employmentTypes',json('[]'),'deadline',expires_at,'postingStatus',posting_status,'completeness','listing_only','sourceUrl',NULL),'baseline_backfill' FROM jobs WHERE id=?").run(`screenshot:${job.id}`,observed,job.id);}
    const state=db.prepare("INSERT INTO job_user_state VALUES(?,1,'apply_planned',0,0,?,?,?,?,?,?)");for(const job of all)state.run(job.id,"포트폴리오 문구를 확인하고 8월 12일에 지원 예정.","2026-08-07","2026-08-12","2026-08-15",fixedTimes[0],fixedTimes[0]);
  } finally { db.close(); }
}

async function freePort(): Promise<number>{return await new Promise((resolvePort,reject)=>{const s=createServer();s.once("error",reject);s.listen(0,"127.0.0.1",()=>{const address=s.address();const port=typeof address==="object"&&address?address.port:0;s.close(()=>resolvePort(port));});});}
async function waitForServer(url:string,child:ChildProcess){for(let i=0;i<120;i++){if(child.exitCode!==null)throw new Error(`Next server exited: ${child.exitCode}`);try{const r=await fetch(url);if(r.ok)return;}catch{/* server is still starting */}await new Promise(r=>setTimeout(r,250));}throw new Error("Next server startup timed out.");}
async function stabilize(page:Page){await page.evaluate(async()=>{await document.fonts.ready;});await page.waitForTimeout(250);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);if(overflow)throw new Error(`Horizontal overflow at ${page.viewportSize()?.width}px`);}
async function prepare(page:Page,port:number,errors:string[],external:Set<string>){await page.route("**/*",async route=>{const url=route.request().url();if(isAllowedBrowserUrl(url,port))return route.continue();external.add(new URL(url).hostname);if(/tile|openstreetmap|\.png|\.jpg|\.webp/iu.test(url))return route.fulfill({status:200,contentType:"image/png",body:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAAyklEQVR42u3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfg2NAAABF9o4WQAAAABJRU5ErkJggg==","base64")});return route.abort("blockedbyclient");});page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});page.on("pageerror",e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem("nearby-jobs-onboarding-v1","completed");});}
async function shot(context:BrowserContext,port:number,file:string,path:string,width:number,height:number,action?: (page:Page)=>Promise<void>){const errors:string[]=[];const external=new Set<string>();const page=await context.newPage();await page.setViewportSize({width,height});await prepare(page,port,errors,external);await page.goto(`http://127.0.0.1:${port}${path}`,{waitUntil:"domcontentloaded"});await page.addStyleTag({content:"*,*::before,*::after{animation:none!important;transition:none!important;caret-color:transparent!important}.leaflet-tile-pane{display:none!important}.leaflet-container{background:#e8efe6!important}"});if(action)await action(page);await stabilize(page);await page.screenshot({path:join(output,file),fullPage:false});if(errors.length)throw new Error(`${file} console errors: ${errors.join(" | ")}`);console.log(`captured ${file}; blocked external hosts=${[...external].join(",")||"none"}`);await page.close();}

async function main(){rmSync(work,{recursive:true,force:true});seed();const port=await freePort();const nextBin=resolve(root,"node_modules/next/dist/bin/next");const child=spawn(process.execPath,[nextBin,"dev","-H","127.0.0.1","-p",String(port)],{cwd:root,env:{...process.env,NEARBY_JOBS_DB_PATH:databasePath,NEARBY_JOBS_ENABLE_COLLECTION_UI:"1",NEXT_TELEMETRY_DISABLED:"1"},stdio:["ignore","pipe","pipe"]});let logs="";child.stdout?.on("data",d=>logs+=String(d));child.stderr?.on("data",d=>logs+=String(d));let browser;
  try{await waitForServer(`http://127.0.0.1:${port}`,child);browser=await chromium.launch({headless:true});const context=await browser.newContext({deviceScaleFactor:1});
    await shot(context,port,SCREENSHOT_SPECS[0].file,"/",1440,1000,async p=>{await p.getByRole("button",{name:/필터/}).first().click();await p.getByLabel("데이터 출처").selectOption("manual");await p.getByLabel("정보 완성도").selectOption("listing_only");await p.locator(".filter-grid select").nth(3).selectOption("seoul");await p.getByRole("button",{name:"결과 보기"}).click();await p.locator(".job-title-button").first().click();});
    await shot(context,port,SCREENSHOT_SPECS[1].file,"/collection",1440,1100,async p=>{await p.getByText("저장된 수집 프로필").waitFor();await p.addStyleTag({content:".collection-page{zoom:.55}.collection-overview{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}.collection-overview>.dashboard-toolbar,.collection-overview>.dashboard-filters,.collection-overview>.dashboard-section:first-of-type,.collection-overview>.dashboard-section:nth-of-type(2),.collection-overview>.dashboard-section:has(.dashboard-run-table-wrap){grid-column:1/-1}.collection-panel{padding:14px}.dashboard-metric-grid{gap:6px}.source-overview-card{padding:10px}"});await p.evaluate(()=>{for(const heading of document.querySelectorAll(".dashboard-section h3"))if(["데이터 완성도","수집 효과","제외 키워드 영향"].includes(heading.textContent?.trim()??""))heading.closest<HTMLElement>(".dashboard-section")!.style.display="none";});});
    await shot(context,port,SCREENSHOT_SPECS[2].file,"/collection?tab=execution",1440,1100,async p=>{await p.getByRole("tab",{name:"수집 실행"}).click();await p.getByRole("heading",{name:"저장된 프로필"}).waitFor();await p.addStyleTag({content:".collection-page{zoom:.82}"});await p.evaluate(()=>scrollTo(0,0));});
    await shot(context,port,SCREENSHOT_SPECS[3].file,`/collection?tab=compare&profiles=${profileIds[0]},${profileIds[1]}&period=all&revisionScope=current`,1440,1100,async p=>{await p.getByRole("tab",{name:"프로필 비교"}).click();await p.getByRole("button",{name:/비교하기/}).click();await p.getByText("정확한 공고 ID 중복").waitFor();await p.addStyleTag({content:".collection-page{zoom:.62}.comparison-selector{display:none}.comparison-results{gap:7px}.comparison-results>.collection-panel{padding:9px}.comparison-table th,.comparison-table td{padding:3px}.difference-summary{margin:3px 0}.comparison-grid article{padding:7px}.comparison-grid p{margin:3px 0}"});await p.evaluate(()=>{const panels=[...document.querySelectorAll<HTMLElement>(".comparison-results>.collection-panel")];panels.at(-1)?.remove();const configRows=[...panels[0]!.querySelectorAll<HTMLTableRowElement>("tbody tr")];configRows.forEach((row,index)=>{if(![1,3,4,5,6,8].includes(index))row.style.display="none";});const performanceRows=[...panels[2]!.querySelectorAll<HTMLTableRowElement>("tbody tr")];performanceRows.forEach((row,index)=>{if(![0,1,3,4,6,7].includes(index))row.style.display="none";});scrollTo(0,0);});});
    await shot(context,port,SCREENSHOT_SPECS[4].file,"/",390,844,async p=>{await p.locator(".job-title-button").first().click();await p.locator(".job-workspace").waitFor();await p.addStyleTag({content:".job-primary,.observation-note{display:none!important}.job-card{font-size:.82rem}.job-workspace{padding:12px!important}.job-workspace textarea{min-height:54px!important}.job-workspace .profile-form-grid{gap:6px!important}.job-workspace input{min-height:36px!important}.notice-strip,.workflow-bar{display:none!important}"});await p.evaluate(()=>{const card=document.querySelector(".job-card.selected");if(card)scrollTo(0,card.getBoundingClientRect().top+scrollY-64);});});
    await shot(context,port,SCREENSHOT_SPECS[5].file,"/",390,844,async p=>{await p.getByRole("button",{name:"도움말"}).click();await p.getByRole("button",{name:"시작하기"}).click();await p.locator(".onboarding-labels").waitFor();});
    await context.close();await browser.close();browser=undefined;
    const docs=resolve(root,"docs/images");mkdirSync(docs,{recursive:true});for(const spec of SCREENSHOT_SPECS)cpSync(join(output,spec.file),join(docs,spec.file));
  }catch(error){console.error(logs);throw error;}finally{if(browser)await browser.close();if(child.exitCode===null)child.kill();await new Promise(r=>setTimeout(r,500));rmSync(work,{recursive:true,force:true});}
}
await main();
