import{afterEach,describe,expect,it}from"vitest";import{existsSync,readFileSync,writeFileSync}from"node:fs";import{join}from"node:path";import{createTestDatabase,type TestDatabase}from"./test-database";import{BackupError,createBackup,resolveBackupPath,restoreBackup,verifyBackup}from"../../server/backups/backup-service";
let test:TestDatabase|null=null;afterEach(()=>{test?.cleanup();test=null});
describe("local backup service",()=>{
 it("creates a verified manifest and checksum from SQLite backup API",async()=>{const current=createTestDatabase();test=current;const result=await createBackup(current.path,join(current.directory,"backups"),new Date("2026-08-06T01:02:03Z"));expect(existsSync(result.filePath)).toBe(true);expect(result.manifest).toMatchObject({format:"nearby-jobs-sqlite-backup",version:1,schemaMigration:"0015"});expect(result.manifest.counts.jobs).toBe(0);expect(verifyBackup(result.filePath).manifest.sha256).toMatch(/^[a-f0-9]{64}$/)});
 it("rejects path traversal, corrupt files and incorrect confirmation",async()=>{const current=createTestDatabase();test=current;expect(()=>resolveBackupPath(join(current.directory,"backups"),"../x.sqlite")).toThrow(BackupError);const bad=join(current.directory,"bad.sqlite");writeFileSync(bad,"not sqlite");expect(()=>verifyBackup(bad)).toThrow();await expect(restoreBackup({databasePath:current.path,backupDirectory:join(current.directory,"backups"),file:"x.sqlite",confirmation:"wrong"})).rejects.toThrow(/확인/)});
 it("creates a pre-restore backup and restores a verified temporary database",async()=>{const current=createTestDatabase();test=current;const dir=join(current.directory,"backups"),backup=await createBackup(current.path,dir,new Date("2026-08-06T01:00:00Z"));current.database.close();const restored=await restoreBackup({databasePath:current.path,backupDirectory:dir,file:backup.manifest.file,confirmation:"RESTORE DATABASE"});expect(restored.preRestoreBackup.format).toBe("nearby-jobs-sqlite-backup");expect(readFileSync(current.path).subarray(0,15).toString()).toBe("SQLite format 3")});
 it("rejects restoration while a manual collection is active",async()=>{const current=createTestDatabase();test=current;const dir=join(current.directory,"backups"),backup=await createBackup(current.path,dir);await expect(restoreBackup({databasePath:current.path,backupDirectory:dir,file:backup.manifest.file,confirmation:"RESTORE DATABASE",activeRun:true})).rejects.toThrow(/활성 수집/)})
 it("uses a bounded custom filename and reports the real provenance table",async()=>{const current=createTestDatabase();test=current;const result=await createBackup(current.path,join(current.directory,"backups"),new Date("2026-08-06T00:00:00Z"),"manual-safe.sqlite");expect(result.manifest.file).toBe("manual-safe.sqlite");expect(result.manifest.counts.provenance).toBe(0);await expect(createBackup(current.path,join(current.directory,"backups"),new Date(),"../unsafe.sqlite")).rejects.toThrow()})
});
