import type Database from "better-sqlite3";
import type { CanonicalJob } from "../../domain/canonical-job";
import { daysSince, type JobFreshness } from "../../services/job-freshness";
type Snapshot={title:string;company:string;location:string|null;salary:string;employmentTypes:string[];deadline:string|null;postingStatus:string;completeness:string;sourceUrl:string};
const snap=(job:CanonicalJob,completeness:string):Snapshot=>({title:job.title.slice(0,300),company:job.companyName.slice(0,300),location:job.addressOriginalText?.slice(0,500)??null,salary:job.salary.originalText.slice(0,300),employmentTypes:[...job.employmentTypes].sort(),deadline:job.expiresAt,postingStatus:job.postingStatus,completeness,sourceUrl:(job.canonicalUrl??job.sourceUrl).slice(0,500)});
export class JobObservationRepository{
 constructor(private db:Database.Database){}
 observe(input:{jobId:string;runId:string;job:CanonicalJob;contentHash:string;completeness:"listing_only"|"detail_complete"|"unknown";observedAt:string}){
  const key=`run:${input.runId}:${input.jobId}`;const prior=this.db.prepare("SELECT * FROM job_observations WHERE job_id=? ORDER BY observed_at DESC,id DESC LIMIT 1").get(input.jobId)as Record<string,unknown>|undefined;const snapshot=snap(input.job,input.completeness);const persistedRun=this.db.prepare("SELECT id FROM ingestion_runs WHERE id=?").get(input.runId)?input.runId:null;
  const result=this.db.prepare("INSERT OR IGNORE INTO job_observations(observation_key,job_id,ingestion_run_id,source,source_posting_id,observed_at,content_hash,completeness,posting_status,snapshot_json,observation_kind)VALUES(?,?,?,?,?,?,?,?,?,?, 'ingestion')").run(key,input.jobId,persistedRun,input.job.source,input.job.sourcePostingId,input.observedAt,input.contentHash,input.completeness,input.job.postingStatus,JSON.stringify(snapshot));if(!result.changes)return null;const id=Number(result.lastInsertRowid);
  if(prior&&String(prior.content_hash)!==input.contentHash){const before=JSON.parse(String(prior.snapshot_json))as Record<string,unknown>;const changed=Object.keys(snapshot).filter(k=>JSON.stringify(before[k])!==JSON.stringify(snapshot[k as keyof Snapshot]));if(changed.length){const changes=Object.fromEntries(changed.map(k=>[k,{before:before[k]??null,after:snapshot[k as keyof Snapshot]??null}]));this.db.prepare("INSERT INTO job_change_events(job_id,observation_id,changed_at,changed_fields_json,changes_json)VALUES(?,?,?,?,?)").run(input.jobId,id,input.observedAt,JSON.stringify(changed),JSON.stringify(changes));}}return id;
 }
 freshness(now=new Date()):JobFreshness[]{return(this.db.prepare(`SELECT o.job_id,MIN(o.observed_at) first_seen,MAX(o.observed_at) last_seen,COUNT(DISTINCT o.id) observation_count,MAX(c.changed_at) last_changed FROM job_observations o LEFT JOIN job_change_events c ON c.job_id=o.job_id GROUP BY o.job_id`).all()as Record<string,unknown>[]).map(r=>({jobId:String(r.job_id),firstSeen:String(r.first_seen),lastSeen:String(r.last_seen),lastChanged:typeof r.last_changed==="string"?r.last_changed:null,observationCount:Number(r.observation_count),daysSinceLastSeen:daysSince(String(r.last_seen),now),changedSincePrevious:r.last_changed!==null}))}
 history(jobId:string){return{observations:this.db.prepare("SELECT id,observed_at,completeness,posting_status,observation_kind FROM job_observations WHERE job_id=? ORDER BY observed_at DESC,id DESC LIMIT 50").all(jobId),changes:this.db.prepare("SELECT changed_at,changed_fields_json,changes_json FROM job_change_events WHERE job_id=? ORDER BY changed_at DESC,id DESC LIMIT 50").all(jobId)}}
}
