import{copyFileSync,existsSync,mkdirSync,readFileSync,renameSync,rmSync,statSync,writeFileSync}from"node:fs";import{createHash}from"node:crypto";import{basename,dirname,join,relative,resolve}from"node:path";import Database from"better-sqlite3";
export const BACKUP_FORMAT="nearby-jobs-sqlite-backup",BACKUP_VERSION=1;export interface BackupManifest{format:typeof BACKUP_FORMAT;version:1;createdAt:string;application:"NearbyJobsMap";schemaMigration:string|null;sha256:string;counts:Record<string,number|null>;file:string}
const TABLES={jobs:"jobs",ingestionRuns:"ingestion_runs",ingestionItems:"ingestion_items",provenance:"job_provenance",savedProfiles:"saved_collection_profiles",savedViews:"saved_job_views",userJobStates:"job_user_state",observations:"job_observations",changeEvents:"job_change_events"}as const;
export class BackupError extends Error{constructor(public code:string,message:string){super(message);this.name="BackupError"}}
export const sha256File=(path:string)=>createHash("sha256").update(readFileSync(path)).digest("hex");
const count=(db:Database.Database,table:string)=>{const exists=db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table);return exists?Number((db.prepare(`SELECT COUNT(*) count FROM ${table}`).get()as{count:number}).count):null};
export function inspectDatabase(path:string){if(!existsSync(path))throw new BackupError("BACKUP_NOT_FOUND","SQLite 파일을 찾을 수 없습니다.");const db=new Database(path,{readonly:true,fileMustExist:true});try{if(db.pragma("integrity_check",{simple:true})!=="ok")throw new BackupError("BACKUP_CORRUPT","SQLite 무결성 검사에 실패했습니다.");const schema=(db.prepare("SELECT version FROM schema_migrations ORDER BY version DESC LIMIT 1").get()as{version?:string}|undefined)?.version??null;return{schemaMigration:schema,counts:Object.fromEntries(Object.entries(TABLES).map(([key,table])=>[key,count(db,table)]))}}finally{db.close()}}
export function resolveBackupPath(backupDirectory:string,input:string){const root=resolve(backupDirectory),target=resolve(root,input);if(relative(root,target).startsWith("..")||relative(root,target).includes(":"))throw new BackupError("UNSAFE_BACKUP_PATH","백업 디렉터리 밖의 경로는 사용할 수 없습니다.");return target}
export async function createBackup(databasePath:string,backupDirectory:string,now=new Date()){mkdirSync(backupDirectory,{recursive:true});const stamp=now.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/, "Z"),fileName=`nearby-jobs-${stamp}.sqlite`,filePath=resolveBackupPath(backupDirectory,fileName);const db=new Database(databasePath,{readonly:true,fileMustExist:true});try{await db.backup(filePath)}finally{db.close()}const inspected=inspectDatabase(filePath);const manifest:BackupManifest={format:BACKUP_FORMAT,version:1,createdAt:now.toISOString(),application:"NearbyJobsMap",schemaMigration:inspected.schemaMigration,sha256:sha256File(filePath),counts:inspected.counts,file:fileName};writeFileSync(`${filePath}.manifest.json`,JSON.stringify(manifest,null,2),"utf8");return{filePath,manifestPath:`${filePath}.manifest.json`,manifest}}
export function verifyBackup(filePath:string){if(statSync(filePath).size<100)throw new BackupError("BACKUP_CORRUPT","백업 파일이 올바르지 않습니다.");const header=readFileSync(filePath).subarray(0,16).toString("utf8");if(header!=="SQLite format 3\0")throw new BackupError("BACKUP_CORRUPT","SQLite 헤더가 올바르지 않습니다.");const manifestPath=`${filePath}.manifest.json`;if(!existsSync(manifestPath))throw new BackupError("MANIFEST_NOT_FOUND","백업 manifest를 찾을 수 없습니다.");const manifest=JSON.parse(readFileSync(manifestPath,"utf8"))as BackupManifest;if(manifest.format!==BACKUP_FORMAT||manifest.version!==1)throw new BackupError("BACKUP_INCOMPATIBLE","지원하지 않는 백업입니다.");if(manifest.sha256!==sha256File(filePath))throw new BackupError("BACKUP_HASH_MISMATCH","백업 해시가 일치하지 않습니다.");return{manifest,...inspectDatabase(filePath)}}
export async function restoreBackup(args:{databasePath:string;backupDirectory:string;file:string;confirmation:string;activeRun?:boolean}){if(args.confirmation!=="RESTORE DATABASE")throw new BackupError("CONFIRMATION_REQUIRED","정확한 복원 확인 문구가 필요합니다.");if(args.activeRun)throw new BackupError("ACTIVE_RUN","활성 수집 실행 중에는 복원할 수 없습니다.");const source=resolveBackupPath(args.backupDirectory,args.file);const verified=verifyBackup(source);const pre=await createBackup(args.databasePath,args.backupDirectory);const temp=join(dirname(args.databasePath),`.${basename(args.databasePath)}.restore.tmp`);try{copyFileSync(source,temp);inspectDatabase(temp);renameSync(temp,args.databasePath);inspectDatabase(args.databasePath);return{restored:verified.manifest,preRestoreBackup:pre.manifest}}catch(error){if(existsSync(temp))rmSync(temp);copyFileSync(pre.filePath,args.databasePath);throw error}}
