"use client";

import { useEffect, useRef, useState } from "react";
import type { SavedCollectionProfile } from "../../services/saved-collection-profile";
import type { ImportAction, ImportConfirmResult, ImportPreviewResult } from "../../server/collection-profile-transfer/contracts";

type Props={profiles:SavedCollectionProfile[];selectedIds:string[];disabled:boolean;onSelectionChange(ids:string[]):void;onChanged():Promise<void>|void};
type Choice={action:ImportAction;newName:string;replaceConfirmed:boolean};
const STATE_LABEL:Record<string,string>={valid_new:"새 프로필",identical_existing:"동일",name_conflict_different_configuration:"이름 충돌",same_configuration_different_name:"동일 구성",invalid:"오류",unsupported_source:"지원하지 않는 소스",unsupported_preset:"지원하지 않는 프리셋"};

export function ProfileTransferPanel({profiles,selectedIds,disabled,onSelectionChange,onChanged}:Props){
 const [open,setOpen]=useState(false);const [preview,setPreview]=useState<ImportPreviewResult|null>(null);const [choices,setChoices]=useState<Record<string,Choice>>({});const [result,setResult]=useState<ImportConfirmResult|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState("all");const inputRef=useRef<HTMLInputElement>(null);const dialogRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(open)dialogRef.current?.querySelector<HTMLElement>("button,input,select")?.focus();},[open]);
 const close=()=>{if(busy)return;setOpen(false);setPreview(null);setResult(null);setError(null);setChoices({});};
 const trap=(event:React.KeyboardEvent)=>{if(event.key==="Escape"){close();return;}if(event.key!=="Tab"||!dialogRef.current)return;const nodes=[...dialogRef.current.querySelectorAll<HTMLElement>("button:not([disabled]),input:not([disabled]),select:not([disabled])")];if(!nodes.length)return;const first=nodes[0]!,last=nodes.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
 const download=async(allProfiles:boolean)=>{setError(null);const response=await fetch("/api/collection-profiles/export",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(allProfiles?{allProfiles:true}:{profileIds:selectedIds})});if(!response.ok){const body=await response.json();setError(body.error?.message??"프로필을 내보내지 못했습니다.");return;}const blob=await response.blob();const disposition=response.headers.get("content-disposition")??"";const encoded=/filename\*=UTF-8''([^;]+)/u.exec(disposition)?.[1];const name=encoded?decodeURIComponent(encoded):"nearby-jobs-profiles.json";const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};
 const previewFile=async(file:File)=>{setBusy(true);setError(null);setResult(null);try{const form=new FormData();form.append("file",file);const response=await fetch("/api/collection-profiles/import/preview",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"가져오기 파일을 읽지 못했습니다.");setPreview(body);setChoices(Object.fromEntries((body.profiles as ImportPreviewResult["profiles"]).map(p=>[p.exportKey,{action:p.suggestedAction??"skip",newName:"",replaceConfirmed:false}])));}catch(value){setError(value instanceof Error?value.message:"가져오기 파일을 읽지 못했습니다.");}finally{setBusy(false);}};
 const confirm=async()=>{if(!preview)return;setBusy(true);setError(null);try{const actions=preview.profiles.map(p=>({exportKey:p.exportKey,...choices[p.exportKey],expectedRevision:p.conflictingProfile?.revision}));const response=await fetch("/api/collection-profiles/import/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({previewToken:preview.previewToken,actions})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"프로필을 가져오지 못했습니다.");setResult(body);await onChanged();window.dispatchEvent(new CustomEvent("nearby-jobs:profiles-changed"));}catch(value){setError(value instanceof Error?value.message:"프로필을 가져오지 못했습니다.");}finally{setBusy(false);}};
 const shown=preview?.profiles.filter(p=>filter==="all"||(filter==="new"&&p.state==="valid_new")||(filter==="conflict"&&p.state.includes("conflict"))||(filter==="same"&&(p.state==="identical_existing"||p.state==="same_configuration_different_name"))||(filter==="error"&&!p.configurationValid))??[];
 return <div className="profile-transfer"><div className="profile-export-toolbar" aria-label="프로필 가져오기와 내보내기"><div><strong>내보내기 선택 {selectedIds.length}개</strong><p>프로필 구성만 JSON으로 저장합니다.</p></div><div className="profile-actions"><button className="button soft compact" disabled={disabled} onClick={()=>setOpen(true)}>프로필 가져오기</button><button className="button compact" disabled={disabled||!selectedIds.length} onClick={()=>void download(false)}>선택 내보내기</button><button className="button compact" disabled={disabled||!profiles.length} onClick={()=>void download(true)}>모두 내보내기</button><button className="button compact" disabled={disabled||selectedIds.length===profiles.length} onClick={()=>onSelectionChange(profiles.map(p=>p.id))}>전체 선택</button><button className="button compact" disabled={disabled||!selectedIds.length} onClick={()=>onSelectionChange([])}>선택 초기화</button></div></div>{error&&!open&&<p className="collection-error" role="alert">{error}</p>}
 {open&&<div className="profile-editor profile-import-dialog" role="dialog" aria-modal="true" aria-labelledby="profile-import-title" ref={dialogRef} onKeyDown={trap}><div className="section-heading"><div><h3 id="profile-import-title">프로필 가져오기</h3><p>미리보기는 SQLite를 변경하지 않습니다.</p></div><button className="button compact" onClick={close}>닫기</button></div>{error&&<p className="collection-error" role="alert">{error}</p>}{!preview&&!result&&<><label className="profile-drop-zone" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();inputRef.current?.click();}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void previewFile(file);}}>JSON 파일 선택 또는 놓기<input ref={inputRef} type="file" accept="application/json,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void previewFile(file);}}/></label><p aria-live="polite">{busy?"파일을 분석하고 있습니다.":"최대 512 KiB, 100개 프로필"}</p></>}
 {preview&&!result&&<><div className="import-file-meta"><strong>{preview.filename}</strong><span>{preview.fileSize.toLocaleString("ko-KR")} bytes · 형식 v{preview.version} · {preview.profileCount}개</span></div><div className="profile-toolbar"><label>미리보기 필터<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option><option value="new">새 프로필</option><option value="conflict">충돌</option><option value="same">동일</option><option value="error">오류</option></select></label></div><div className="import-preview-list" role="table" aria-label="가져오기 프로필 미리보기">{shown.map(p=>{const choice=choices[p.exportKey]??{action:"skip",newName:"",replaceConfirmed:false};return <article key={p.exportKey} className="import-preview-card" role="row"><div className="section-heading"><h4>{p.importedName||"이름 없음"}</h4><span className="badge">{STATE_LABEL[p.state]??p.state}</span></div><p>{p.source??"정보 없음"} · {p.basePresetId??"정보 없음"}</p>{p.configuration&&<p>{p.configuration.regions.join("+")} · {p.configuration.pages}페이지 · 후보 {p.configuration.maxCandidates}건 · 제외 {p.configuration.exclusion.keywords.length}개</p>}{p.exportedHashMatches===false&&<p className="collection-warning">파일의 정보용 해시와 현재 계산 해시가 다릅니다. 현재 계산값을 사용합니다.</p>}{p.validationErrors.map(e=><p key={e.code} className="collection-error">{e.code}: {e.message}</p>)}{p.availableActions.length>0&&<label>가져오기 작업<select value={choice.action} onChange={e=>setChoices({...choices,[p.exportKey]:{...choice,action:e.target.value as ImportAction}})}>{p.availableActions.map(action=><option key={action} value={action}>{action==="create"?"새로 만들기":action==="skip"?"건너뛰기":action==="rename_and_create"?"이름을 바꿔 새로 만들기":"기존 프로필 바꾸기"}</option>)}</select></label>}{choice.action==="rename_and_create"&&<label>새 이름<input value={choice.newName} onChange={e=>setChoices({...choices,[p.exportKey]:{...choice,newName:e.target.value}})}/></label>}{choice.action==="replace_existing"&&<label className="checkbox-line"><input type="checkbox" checked={choice.replaceConfirmed} onChange={e=>setChoices({...choices,[p.exportKey]:{...choice,replaceConfirmed:e.target.checked}})}/>revision {p.conflictingProfile?.revision} 기존 프로필 교체 확인</label>}</article>;})}</div><div className="profile-actions"><button className="button primary" disabled={busy} onClick={()=>void confirm()}>선택한 작업 가져오기</button><button className="button soft" onClick={close}>취소</button></div></>}
 {result&&<div aria-live="polite"><h4>가져오기 완료</h4><div className="summary-grid"><span>생성 <strong>{result.created}</strong></span><span>기존 프로필 변경 <strong>{result.replaced}</strong></span><span>변경 없음 <strong>{result.unchanged}</strong></span><span>건너뜀 <strong>{result.skipped}</strong></span><span>오류 미선택 <strong>{result.invalidNotSelected}</strong></span></div><div className="profile-actions"><button className="button primary" onClick={close}>저장된 프로필 보기</button><a className="button soft" href="/collection?tab=compare">가져온 프로필 비교하기</a></div></div>}</div>}</div>;
}
