"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { SavedCollectionProfile, SavedCollectionProfileInput } from "../../services/saved-collection-profile";
import type { CollectionPreset } from "../../sources/collection/collection-presets";
import { DEFAULT_EXCLUSION_FIELDS, EXCLUSION_FIELDS, normalizeCollectionExclusionConfig, splitExclusionKeywordInput, type CollectionExclusionConfig, type ExclusionField } from "../../services/collection-exclusion";

type Seed = { preset: CollectionPreset; pages: number; maxCandidates: number; exclusion: CollectionExclusionConfig };
type Props = { enabled: boolean; busy: boolean; presets: CollectionPreset[]; seed: Seed; selectedProfileId: string | null; onSelect(profile: SavedCollectionProfile): void; onProfilesChanged?(): void };
const FIELD_LABELS: Record<ExclusionField,string> = { title:"공고명",company:"회사명",location:"지역",category:"직종·카테고리",employment_type:"고용형태",work_schedule:"근무 일정" };

export function SavedProfilesPanel({ enabled, busy, presets, seed, selectedProfileId, onSelect, onProfilesChanged }: Props) {
  const [profiles,setProfiles]=useState<SavedCollectionProfile[]>([]); const [editing,setEditing]=useState<SavedCollectionProfileInput & { id?:string; expectedRevision?:number } | null>(null);
  const [search,setSearch]=useState(""); const [source,setSource]=useState<"all"|"jobkorea"|"albamon">("all"); const [favorites,setFavorites]=useState(false);
  const [error,setError]=useState<string|null>(null); const [dirty,setDirty]=useState(false);
  const load=useCallback(async()=>{ if(!enabled)return; const response=await fetch("/api/collection-profiles",{cache:"no-store"}); const body=await response.json(); if(response.ok)setProfiles(body.profiles??[]); else setError(body.error?.message??"저장 프로필을 불러오지 못했습니다.");},[enabled]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!editing||!dirty)return; const warn=(event:BeforeUnloadEvent)=>event.preventDefault(); window.addEventListener("beforeunload",warn); return()=>window.removeEventListener("beforeunload",warn);},[editing,dirty]);
  const visible=useMemo(()=>profiles.filter((p)=>(source==="all"||p.source===source)&&(!favorites||p.isFavorite)&&p.name.toLocaleLowerCase("ko").includes(search.trim().toLocaleLowerCase("ko"))),[profiles,source,favorites,search]);
  const createSeed=()=>{const p=seed.preset;setEditing({name:`${p.label} 프로필`,source:p.source,basePresetId:p.id,strategy:p.source==="jobkorea"?"jobkorea_keyword":"albamon_today",keyword:p.source==="jobkorea"?p.keyword:null,regions:p.regions,pages:seed.pages,maxCandidates:seed.maxCandidates,allowListingFallback:p.source==="jobkorea"?p.allowListingFallback:false,exclusion:seed.exclusion,isFavorite:false});setDirty(false);};
  const edit=(p:SavedCollectionProfile)=>{setEditing({id:p.id,expectedRevision:p.revision,name:p.name,source:p.source,basePresetId:p.basePresetId,strategy:p.strategy,keyword:p.keyword,regions:p.regions,pages:p.pages,maxCandidates:p.maxCandidates,allowListingFallback:p.allowListingFallback,exclusion:p.exclusion,isFavorite:p.isFavorite});setDirty(false);};
  const close=()=>{if(dirty&&!window.confirm("저장하지 않은 변경 사항을 버릴까요?"))return;setEditing(null);setDirty(false);};
  const save=async()=>{if(!editing)return;setError(null);const {id,expectedRevision,...profile}=editing;const response=await fetch(id?`/api/collection-profiles/${id}`:"/api/collection-profiles",{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(id?{...profile,expectedRevision}:profile)});const body=await response.json();if(!response.ok){setError(body.error?.message??"프로필을 저장하지 못했습니다.");return;}setEditing(null);setDirty(false);await load();onProfilesChanged?.();onSelect(body.profile);};
  const action=async(url:string,options:RequestInit={method:"POST",headers:{"content-type":"application/json"},body:"{}"})=>{const response=await fetch(url,options);const body=response.status===204?{}:await response.json();if(!response.ok){setError(body.error?.message??"프로필 작업에 실패했습니다.");return null;}await load();onProfilesChanged?.();return body.profile as SavedCollectionProfile|undefined;};
  const remove=async(p:SavedCollectionProfile)=>{if(!window.confirm(`'${p.name}' 프로필을 삭제할까요? 수집 이력과 공고는 삭제되지 않습니다.`))return;await action(`/api/collection-profiles/${p.id}`,{method:"DELETE"});};
  return <section className="collection-panel saved-profile-panel" aria-labelledby="saved-profile-heading"><div className="section-heading"><div><h2 id="saved-profile-heading">저장된 프로필</h2><p>SQLite에 저장한 구성을 나중에 다시 사용할 수 있습니다.</p></div><button type="button" className="button soft" disabled={busy} onClick={createSeed}>현재 설정을 프로필로 저장</button></div>
    <div className="profile-toolbar"><label>프로필 검색<input value={search} onChange={e=>setSearch(e.target.value)} /></label><label>소스<select value={source} onChange={e=>setSource(e.target.value as typeof source)}><option value="all">전체</option><option value="jobkorea">잡코리아</option><option value="albamon">알바몬</option></select></label><label className="checkbox-line"><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)} /> 즐겨찾기만</label></div>
    {error&&<p className="collection-error" role="alert">{error}</p>}
    {!profiles.length?<div className="dashboard-empty"><p>저장된 프로필이 없습니다.<br/>기본 프리셋을 원하는 설정으로 조정한 뒤 프로필로 저장해 보세요.</p><button className="button soft" onClick={createSeed}>프로필 만들기</button></div>:
      !visible.length?<p className="dashboard-empty">조건에 맞는 저장 프로필이 없습니다.</p>:<div className="saved-profile-grid">{visible.map(p=><article key={p.id} className={`saved-profile-card ${selectedProfileId===p.id?"selected":""}`}><div className="section-heading"><h3>{p.name}</h3><button className="favorite-toggle" aria-label={`${p.name} ${p.isFavorite?"즐겨찾기 해제":"즐겨찾기"}`} aria-pressed={p.isFavorite} onClick={()=>void action(`/api/collection-profiles/${p.id}/favorite`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedRevision:p.revision,isFavorite:!p.isFavorite})})}>{p.isFavorite?"★":"☆"}</button></div><p><span className={`badge source-${p.source}`}>{p.source==="jobkorea"?"잡코리아":"알바몬"}</span> {p.regions.map(r=>r==="seoul"?"서울":"경기").join("+")}</p><p>{p.keyword??"오늘 등록"} · {p.pages}페이지 · 후보 {p.maxCandidates}건</p><small>제외 {p.exclusion.keywords.length}개 · revision {p.revision} · 최근 사용 {p.lastUsedAt?new Date(p.lastUsedAt).toLocaleString("ko-KR"):"없음"}</small><div className="profile-actions"><button className="button primary compact" disabled={busy} onClick={()=>onSelect(p)}>선택</button><button className="button compact" disabled={busy||selectedProfileId===p.id&&busy} onClick={()=>edit(p)}>편집</button><button className="button compact" disabled={busy} onClick={()=>void action(`/api/collection-profiles/${p.id}/duplicate`)}>복제</button><button className="button danger-soft compact" disabled={busy} onClick={()=>void remove(p)}>삭제</button></div></article>)}</div>}
    {editing&&<ProfileEditor value={editing} preset={presets.find(p=>p.id===editing.basePresetId)!} dirty={dirty} onChange={value=>{setEditing(value);setDirty(true);}} onSave={()=>void save()} onClose={close}/>}</section>;
}

function ProfileEditor({value,preset,dirty,onChange,onSave,onClose}:{value:SavedCollectionProfileInput&{id?:string;expectedRevision?:number};preset:CollectionPreset;dirty:boolean;onChange(v:typeof value):void;onSave():void;onClose():void}){
 const dialogRef=useRef<HTMLDivElement>(null); useEffect(()=>{dialogRef.current?.querySelector<HTMLElement>("input:not([disabled]), textarea, button")?.focus();},[]);
 const trap=(event:React.KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();onClose();return;}if(event.key!=="Tab"||!dialogRef.current)return;const focusable=[...dialogRef.current.querySelectorAll<HTMLElement>("button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled])")];if(!focusable.length)return;const first=focusable[0]!,last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
 const set=<K extends keyof SavedCollectionProfileInput>(key:K,next:SavedCollectionProfileInput[K])=>onChange({...value,[key]:next});
 const exclusionText=value.exclusion.keywords.join(", ");
 return <div ref={dialogRef} className="profile-editor" role="dialog" aria-modal="true" aria-labelledby="profile-editor-title" onKeyDown={trap}><div className="section-heading"><h3 id="profile-editor-title">{value.id?"프로필 편집":"프로필 만들기"}</h3><button className="button compact" onClick={onClose}>닫기</button></div><p>소스와 기본 프리셋은 생성 후 변경되지 않습니다. 임시 실행 한도 축소는 프로필을 수정하지 않습니다.</p><div className="profile-form-grid"><label>프로필 이름<input value={value.name} aria-invalid={value.name.trim().length<2} onChange={e=>set("name",e.target.value)}/></label><label>소스<input value={value.source==="jobkorea"?"잡코리아":"알바몬"} disabled/></label><label>기본 프리셋<input value={preset.label} disabled/></label>{value.source==="jobkorea"&&<label>키워드<input value={value.keyword??""} onChange={e=>set("keyword",e.target.value)}/></label>}<fieldset><legend>지역</legend>{(["seoul","gyeonggi"] as const).map(region=><label key={region}><input type="checkbox" checked={value.regions.includes(region)} onChange={()=>set("regions",value.regions.includes(region)?value.regions.filter(r=>r!==region):[...value.regions,region])}/>{region==="seoul"?"서울":"경기"}</label>)}</fieldset><label>페이지<input type="number" min="1" max={preset.pages} value={value.pages} onChange={e=>set("pages",Number(e.target.value))}/></label><label>최대 후보<input type="number" min="1" max={preset.maxDetails} value={value.maxCandidates} onChange={e=>set("maxCandidates",Number(e.target.value))}/></label><label className="checkbox-line"><input type="checkbox" checked={value.isFavorite} onChange={e=>set("isFavorite",e.target.checked)}/>즐겨찾기</label></div><label>제외 키워드 (쉼표/줄바꿈)<textarea value={exclusionText} onChange={e=>{try{set("exclusion",normalizeCollectionExclusionConfig({keywords:splitExclusionKeywordInput(e.target.value),fields:value.exclusion.fields.length?value.exclusion.fields:DEFAULT_EXCLUSION_FIELDS}));}catch{/* submit validation presents the bounded error */}}}/></label><fieldset className="exclusion-fields"><legend>제외 필드</legend>{EXCLUSION_FIELDS.map(field=><label key={field}><input type="checkbox" checked={value.exclusion.fields.includes(field)} onChange={()=>set("exclusion",{...value.exclusion,fields:value.exclusion.fields.includes(field)?value.exclusion.fields.filter(f=>f!==field):[...value.exclusion.fields,field]})}/>{FIELD_LABELS[field]}</label>)}</fieldset><div className="profile-actions"><button className="button primary" disabled={!dirty&&Boolean(value.id)} onClick={onSave}>저장</button><button className="button soft" onClick={onClose}>취소</button></div></div>;
}
